version: '3'

services:
  server:
    build: ./
    ports:
      - '3000:3000'
    links:
      - redis
    environment:
      - REDIS_PORT=redis://cache
  redis:
    image: redis
    container_name: cache
    expose:
      - '6379'
